name: "❓ Ask for help"
description: "Submit any question related to Uptime Kuma"
#title: "[Help] "
labels: [help]
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "⚠️ Please verify that this bug has NOT been raised before."
      description: "Search in the issues sections by clicking [HERE](https://github.com/louislam/uptime-kuma/issues?q=)"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    attributes:
      label: "🛡️ Security Policy"
      description: Please review the security policy before reporting security related issues/bugs.
      options:
        - label: I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
          required: true
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "📝 Describe your problem"
      description: "Please walk us through it step by step."
      placeholder: "Describe what are you asking for..."
  - type: input
    id: uptime-kuma-version
    attributes:
      label: "🐻 Uptime-Kuma Version"
      description: "Which version of Uptime-Kuma are you running? Please do NOT provide the docker tag such as latest or 1"
      placeholder: "Ex. 1.10.0"
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: "💻 Operating System and Arch"
      description: "Which OS is your server/device running on?"
      placeholder: "Ex. Ubuntu 20.04 x86"
    validations:
      required: true
  - type: input
    id: browser-vendor
    attributes:
      label: "🌐 Browser"
      description: "Which browser are you running on?"
      placeholder: "Ex. Google Chrome 95.0.4638.69"
    validations:
      required: true
  - type: input
    id: docker-version
    attributes:
      label: "🐋 Docker Version"
      description: "If running with Docker, which version are you running?"
      placeholder: "Ex. Docker 20.10.9 / K8S / Podman"
    validations:
      required: false
  - type: input
    id: nodejs-version
    attributes:
      label: "🟩 NodeJS Version"
      description: "If running with Node.js? which version are you running?"
      placeholder: "Ex. 14.18.0"
    validations:
      required: false
